version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=estate_planning
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your-password
    ports:
      - "5432:5432"

  backend:
    build: ./estate_planning_backend
    command: python manage.py runserver 0.0.0.0:5003
    volumes:
      - ./estate_planning_backend:/app
    ports:
      - "5003:5003"
    environment:
      - DEBUG=True
      - DB_HOST=db
    depends_on:
      - db

volumes:
  postgres_data: 