version: '3.8'

services:
  frontend:
    build:
      context: ./estate-planning-web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5003/api

  backend:
    build:
      context: ./estate_planning_backend
      dockerfile: Dockerfile.prod
    command: gunicorn estate_planning_backend.wsgi:application --bind 0.0.0.0:5003
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 5003
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    extends:
      file: docker-compose.yml
      service: db

volumes:
  postgres_data:
  static_volume:
  media_volume: 